version: '2'
services:
  web:
    build: .
    ports:
      - "5010:5000"
    volumes:
      - C:\Users\KVanDyk\Projects\RESTapiCourse\fromZero:/opt/pets-api
    links:
      - db:mongodb
    container_name: petsapi_web_1
  db:
    image: mongo:3.0.2
    container_name: petsapi_db_1
